In [ ]:
1. # REAL WORLD: DATA PRODUCT [APPS, SERVICES, WEBSITES, ETC.], DATA ANALYSIS [REPORTS, VISUALIZATIONS, ETC.]
# DATA ENGINEER: COLLECTING AND STORING DATA
	2. # - RAW DATA: [PHYSICAL SENSORS, SURVEYS, SIMULATIONS, EXPERIMENTS, DATA USAGE, ETC.]
	3. # - DATA PROCESSING AND STORAGE: [SQL DATABASE, CSV, EXCEL, CLOUD, ETC.]
# DATA ANALYST / DATA SCIENTIST:
	4. # - CLEANING AND ORGANIZING DATA: [BACK AND FORTH WITH COLLECTION AND STORAGE, REORGANIZING DATA, DEALING WITH MISSING DATA, RESTRUCTURING DATA, ETC.]
	5. # - EXPLORATORY DATA ANALYSIS: [STATISTICAL ANALYSIS, VISUALIZATION, COMMUNICATION] -> PERFORM DATA ANALYSIS AND MAKE A DECISION OR ANSWER QUESTIONS 
# MACHINE LEARNING ENGINEER / DATA SCIENTIST: 
	6. # - MACHINE LEARNING MODELS: SUPERVISED [PREDICT AND OUTCOME] / UNSUPERVISED [DISCOVER PATTERNS IN DATA] LEARNING -> SERVICES, DASHBOARDS, APPLICATIONS -> PREDICT FUTURE OUTCOMES OR GAIN INSIGHT ON DATA 

In [1]:
import numpy as np

In [5]:
mylist = [1,2,3]

In [6]:
type(mylist)

list

In [7]:
myarr = np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
mylist0 = [1,2,"a", "b", ["x",2,"z"]]

In [10]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
type(mymatrix)

list

In [13]:
mymatrixarr = np.array(mymatrix)

In [14]:
mymatrixarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
type(mymatrixarr)

numpy.ndarray

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
len(np.linspace(1,10,10))

10

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.random.randint(0,101)

61

In [27]:
np.random.randint(0,100,10)

array([23, 44, 52, 81, 30, 34, 70, 66, 49, 92])

In [28]:
np.random.randint(0,100,(3,2))

array([[ 6, 80],
       [95, 81],
       [93, 36]])

In [29]:
test_arr1 = np.arange(0,10)

In [30]:
test_arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
len(test_arr1)

10

In [32]:
test_arr1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
test_arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
test_arr2 = np.random.randint(0,100,10)

In [35]:
test_arr2

array([42, 43,  6, 77, 84, 99, 42, 22, 49, 46])

In [36]:
test_arr2.max()

99

In [37]:
test_arr2.min()

6

In [38]:
test_arr2.argmax()

5

In [39]:
test_arr2.argmin()

2

In [40]:
test_arr1.dtype

dtype('int64')

In [41]:
test_arr2.dtype

dtype('int64')

In [42]:
test_arr1.shape

(10,)

In [43]:
shape(test_arr1.reshape(5,2))

NameError: name 'shape' is not defined

In [44]:
test_arr3 = test_arr1.reshape(2,5)

In [45]:
test_arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
test_arr3.shape

(2, 5)

In [47]:
myarr1 = np.arange(0,10)

In [48]:
myarr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
myarr1[1:5]

array([1, 2, 3, 4])

In [50]:
myarr1[0:5]

array([0, 1, 2, 3, 4])

In [51]:
myarr1[:5]

array([0, 1, 2, 3, 4])

In [52]:
myarr1[5:]

array([5, 6, 7, 8, 9])

In [53]:
# this is called boradcasting
myarr1[1:4] = 100

In [54]:
myarr1

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [55]:
myarr11 = np.array(myarr1)

In [56]:
# this is called slicing an array
myarr1_slice = myarr11[1:4]

In [57]:
myarr1_slice

array([100, 100, 100])

In [58]:
myarr1_slice = myarr11[1:4]

In [59]:
myarr1_slice

array([100, 100, 100])

In [60]:
myarr11

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [61]:
myarr1_slice[:] = 1000

In [62]:
myarr1_slice

array([1000, 1000, 1000])

In [63]:
myarr11

array([   0, 1000, 1000, 1000,    4,    5,    6,    7,    8,    9])

In [64]:
type(myarr11)

numpy.ndarray

In [66]:
myarr1

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [67]:
myarr1copy = myarr1.copy()

In [68]:
myarr1copy

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [69]:
myarr1copy[:] = 100

In [70]:
myarr1copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [71]:
myarr1
# changes to copy does not change the original array unlike slice 

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [73]:
# 2D arrays
myarr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [74]:
myarr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
myarr_2d.shape

(3, 3)

In [76]:
myarr_2d[1][1]

5

In [77]:
myarr_2d[1,1]

5

In [79]:
myarr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [81]:
#conditional selection 
myarr1[1:4] = np.arange(1,4)

In [82]:
myarr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
myarr1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [84]:
bool_arr1 = myarr1 > 5

In [85]:
bool_arr1

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [86]:
myarr1[myarr1>5]

array([6, 7, 8, 9])

In [88]:
myarr1[~(myarr1>5)]

array([0, 1, 2, 3, 4, 5])

In [89]:
myarr1[~bool_arr1]

array([0, 1, 2, 3, 4, 5])

In [2]:
arr1 = np.arange(20)

In [3]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
arr1 + arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [5]:
arr1 - arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr1 * arr1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [7]:
arr1 / arr1

/var/folders/z6/thynd_jn7ng6md8_4_sn26hr0000gn/T/ipykernel_74344/3759155054.py:1: RuntimeWarning: invalid value encountered in divide
  arr1 / arr1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
arr1 // arr1

/var/folders/z6/thynd_jn7ng6md8_4_sn26hr0000gn/T/ipykernel_74344/3522756561.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr1 // arr1


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
arr1 % arr1

/var/folders/z6/thynd_jn7ng6md8_4_sn26hr0000gn/T/ipykernel_74344/275515262.py:1: RuntimeWarning: divide by zero encountered in remainder
  arr1 % arr1


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr1 ** arr1

array([                   1,                    1,                    4,
                         27,                  256,                 3125,
                      46656,               823543,             16777216,
                  387420489,          10000000000,         285311670611,
              8916100448256,      302875106592253,    11112006825558016,
         437893890380859375,                    0, -2863221430593058543,
        -497033925936021504,  6353754964178307979])

In [12]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [13]:
1/arr1

/var/folders/z6/thynd_jn7ng6md8_4_sn26hr0000gn/T/ipykernel_74344/393800717.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [15]:
arr1.max()

19

In [16]:
arr1.min()

0

In [17]:
arr1.mean()

9.5

In [19]:
arr1.var()

33.25

In [20]:
arr1.std()

5.766281297335398

In [21]:
arr2 = arr1.reshape(5,4)

In [22]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
arr2.sum()

190

In [25]:
arr2.sum(axis=0)
# this means take the sum across all columns

array([40, 45, 50, 55])

In [26]:
arr2.sum(axis=1)
#thsi means the sume of elements across all rows 

array([ 6, 22, 38, 54, 70])